version: "3.8"

services:
  postgres:
    image: pgvector/pgvector:pg15
    container_name: codesense-postgres
    restart: always
    environment:
      POSTGRES_USER: kartikey
      POSTGRES_PASSWORD: npg_8twMdf6oLWxu
      POSTGRES_DB: codesense
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: codesense-redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_data: